# Generated by Django 3.0.8 on 2020-08-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speech_text', models.CharField(max_length=200)),
                ('emotion', models.CharField(max_length=20)),
            ],
        ),
    ]
